objects/Account.object
<CustomObject>
    <fields>
        <fullName>DUNS__c</fullName>
        <label>DUNS</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Disabled_Veteran_Owned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disabled Veteran-Owned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disadvantaged_Women_Owned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disadvantaged Women-Owned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disadvantaged__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disadvantaged</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EIN__c</fullName>
        <label>EIN</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Firm_ID__c</fullName>
        <description>EHB Firm ID</description>
        <externalId>true</externalId>
        <label>Firm ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Firm_Type__c</fullName>
        <description>Firm Types</description>
        <label>Firm Type</label>
        <picklist>
            <picklistValues>
                <fullName>NASA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-NASA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Hubzone__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hubzone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Veteran_Owned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Veteran-Owned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Woman_Owned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Woman-Owned</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Awards__c.object
<CustomObject>
    <description>Object to capture all prior awards</description>
    <fields>
        <fullName>Agency__c</fullName>
        <label>Agency</label>
        <picklist>
            <picklistValues>
                <fullName>NASA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-NASA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Award_ID__c</fullName>
        <description>EHB Award ID</description>
        <externalId>true</externalId>
        <label>Award ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Award_Type__c</fullName>
        <label>Award Type</label>
        <picklist>
            <picklistValues>
                <fullName>NASA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-NASA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contract_Status__c</fullName>
        <label>Contract Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive and awaiting closeout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Administration</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <picklist>
            <picklistValues>
                <fullName>Phase I</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phase II</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <picklist>
            <picklistValues>
                <fullName>SBIR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>STTR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Proposal_Tite_del__c</fullName>
        <label>Proposal Title</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Proposal__c</fullName>
        <externalId>true</externalId>
        <label>Proposal #</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Award</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Firm__c</field>
                <operation>equals</operation>
                <valueField>Awards__c.Firm__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Awards__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Related_Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Solicitation_ID__c</fullName>
        <externalId>true</externalId>
        <label>Solicitation</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Technology_Area__c</fullName>
        <label>Technology Area</label>
        <type>TextArea</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>Contract #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ContactId__c</fullName>
        <externalId>true</externalId>
        <label>ContactId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Agency__c</fullName>
        <label>Agency</label>
        <picklist>
            <picklistValues>
                <fullName>Department of Agriculture (DOA)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Department of Commerce (DOC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Department of Defense (DOD)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National Aeronautics and Space Administration (NASA)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract #</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EHBId__c</fullName>
        <externalId>true</externalId>
        <label>EHBId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Proposal__c</fullName>
        <formula>Related_Award__r.Proposal__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Proposal #</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Award</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Opportunity and Award Firm should be the same</errorMessage>
            <filterItems>
                <field>Awards__c.Firm__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Awards__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Technology_Area__c</fullName>
        <label>Opportunity Technology Area</label>
        <picklist>
            <picklistValues>
                <fullName>Launch Propulsion Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Space Propulsion Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Space Power and Energy Storage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Robotics, Telerobotics and Autonomous Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Communication and Navigation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Human Health, Life Support and Habitation Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Human Exploration Destination Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Science Instruments, Observatories and Sensor Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entry, Descent and Landing Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nanotechnology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Modeling, Simulation, Information Technology and Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Materials, Structural, Mechanical Systems and Manufacturing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ground and Launch System</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thermal Management Systems</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/OpportunityAward__c.object
<CustomObject>
    <fields>
        <fullName>Related_Award__c</fullName>
        <label>Related Award</label>
        <referenceTo>Awards__c</referenceTo>
        <relationshipLabel>Related Opportunity</relationshipLabel>
        <relationshipName>Related_Opportunity</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Related_Opportunity__c</fullName>
        <label>Related Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Related Award</relationshipLabel>
        <relationshipName>Related_Award</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity Award Relation</label>
    <nameField>
        <displayFormat>OPA-{0000000}</displayFormat>
        <label>OpportunityAward Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Award Relation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/SendOpportunityToEHB.cls
public with sharing class SendOpportunityToEHB {

	public static Map<String,String> SendOpportunityToEHB(List<Opportunity> opps, Map<String, String> calloutResponse){

		Http h = new Http();
		// Instantiate a new HTTP request, specify the method (POST) as well as the endpoint
		HttpRequest req = new HttpRequest();  
		req.setTimeout(10000);
		req.setHeader('Content-Type','application/json');
		req.setHeader('Authorization', 'AuthHeader');
		req.setEndpoint('URL' + 'MethodName');
		req.setMethod('POST');

        SalesforceEHBDataRequest request = new SalesforceEHBDataRequest();
        request.SalesforceEHBData = new cls_SalesforceEHBData();
        request.SalesforceEHBData.opportunities = new List<cls_opportunities>();

//        cls_opportunities optyData = new cls_opportunities();
        List<cls_opportunities> lo = new List<cls_opportunities>();

        //String oppId;
        for(Opportunity opty : opps){
            //Opportunity Data
            //Opportunity opty = [Select Id,Agency__c,EHBId__c,Name,Contract__c,CloseDate,Account.Id from Opportunity where Id = :oppId];
            cls_opportunities optyData = new cls_opportunities();
            optyData.id = opty.EHBId__c;
            optyData.title = opty.Name;
            optyData.contract = opty.Contract__c;
            optyData.agency = opty.Agency__c;
            optyData.fiscalYear = opty.CloseDate;
            optyData.sfId = opty.Id;

            //Firm Data
            FirmData fData = new FirmData();
            Account act = [Select Id,Firm_Type__c,Name,BillingStreet,BillingCity,BillingState,BillingPostalCode,Website,
                                    EIN__c,DUNS__c,Phone,Disadvantaged__c,Woman_Owned__c,Disadvantaged_Women_Owned__c,Firm_ID__c,
                                    Hubzone__c,Veteran_Owned__c,Disabled_Veteran_Owned__c from Account where Id = :opty.Account.Id];
            fdata.id = act.Firm_ID__c;
            fdata.type = act.Firm_Type__c;
            fdata.name = act.Name;
            fdata.street = act.BillingStreet;
            fdata.city = act.BillingCity;
            fdata.st = act.BillingState;
            fdata.zip = act.BillingPostalCode;
            fdata.url = act.Website;
            fdata.ein = act.EIN__c;
            fdata.duns = act.DUNS__c;
            fdata.phone = act.Phone;
            fdata.minorityOwned = act.Disadvantaged__c;
            fdata.women = act.Woman_Owned__c;
            fdata.minorityWomen = act.Disadvantaged_Women_Owned__c;
            fdata.hubzone = act.Hubzone__c;
            fdata.veteran = act.Veteran_Owned__c;
            fdata.disabled = act.Disabled_Veteran_Owned__c;
            fdata.sfId = act.Id;
            optyData.firm = fData;

            //Awards Data
            List<OpportunityAward__c> optyAward = [Select Related_Award__r.Award_ID__c,Related_Award__r.Id,Related_Award__r.Award_Type__c,
                                                            Related_Award__r.Name,Related_Award__r.Proposal__c,Related_Award__r.Proposal_Tite_del__c,
                                                            Related_Award__r.Agency__c,Related_Award__r.Program__c,Related_Award__r.Phase__c,
                                                            Related_Award__r.Amount__c,Related_Award__r.Solicitation_Id__c,Related_Award__r.Technology_Area__c,
                                                            Related_Award__r.Contract_Status__c from OpportunityAward__c where Related_Opportunity__c = :opty.Id];
            List<Award> awardList = new List<Award>();
            for(Integer i = 0; i<optyAward.size(); i++){
                Award awardData = new Award();
                awardData.id = optyAward.get(i).Related_Award__r.Award_ID__c;
                awardData.sfId = optyAward.get(i).Related_Award__r.Id;
                awardData.type = optyAward.get(i).Related_Award__r.Award_Type__c;
                awardData.contract = optyAward.get(i).Related_Award__r.Name;
                awardData.proposal = optyAward.get(i).Related_Award__r.Proposal__c;
                awardData.title = optyAward.get(i).Related_Award__r.Proposal_Tite_del__c;
                awardData.agency = optyAward.get(i).Related_Award__r.Agency__c;
                awardData.program = optyAward.get(i).Related_Award__r.Program__c;
                awardData.phase = optyAward.get(i).Related_Award__r.Phase__c;
                awardData.amount = Integer.valueOf(optyAward.get(i).Related_Award__r.Amount__c);
                awardData.solicitation = optyAward.get(i).Related_Award__r.Solicitation_Id__c;
                awardData.techArea = optyAward.get(i).Related_Award__r.Technology_Area__c;
                awardData.contact_status = optyAward.get(i).Related_Award__r.Contract_Status__c;
                awardList.add(awardData);
            }
            optyData.awards = awardList;

            //Contacts Data
            List<OpportunityContactRole> optyContacts = [Select ContactId,Role,Contact.FirstName, Contact.LastName, Contact.Phone,Contact.ContactId__c,
                                                                Contact.Email,Contact.Id From OpportunityContactRole where OpportunityId = :opty.Id];
            List<Contact> contactList = new List<Contact>();
            for(Integer i = 0; i<optyContacts.size(); i++){
                    Contact contactData = new Contact();
                contactData.firstName = optyContacts.get(i).Contact.FirstName;
                contactData.lastName = optyContacts.get(i).Contact.LastName;
                contactData.phone = optyContacts.get(i).Contact.Phone;
                contactData.email = optyContacts.get(i).Contact.Email;
                contactData.id = optyContacts.get(i).Contact.ContactId__c;
                contactData.sfId = optyContacts.get(i).Contact.Id;
                contactData.role = optyContacts.get(i).Role;
                contactList.add(contactData);
            }
            optyData.contacts = contactList;
            lo.add(optyData);
        }
        request.SalesforceEHBData.opportunities = lo;
        System.debug('optyData----' + JSON.serialize(request));

        /*HttpResponse response = h.send(req);
        System.debug('++ response code Status Update' + response.getStatusCode());
        if(response.getStatusCode() != 200){
            System.debug('++ response' + response.getBody());
        }
        else{
            calloutResponse.put(oppId,'Success');
        }*/
		return calloutResponse;
	}

    public class SalesforceEHBDataRequest{
        cls_SalesforceEHBData SalesforceEHBData {get;set;}
    }


    public class cls_SalesforceEHBData {
        List<cls_opportunities> opportunities;
    }    

    public class cls_opportunities{
    	public String id {get;set;}
    	public String title {get;set;}
    	public String contract {get;set;}
    	public String agency {get;set;}
    	public Date fiscalYear {get;set;}
    	public String sfId {get;set;}
    	public firmData firm {get;set;}
		public List<Award> awards{get;set;}
		public List<Contact> contacts{get;set;}
    }

	public class FirmData {

        public String id{get;set;}
        public String type{get;set;}
        public String name{get;set;}
        public String street{get;set;}
        public String city{get;set;}
        public String st{get;set;}
        public String zip{get;set;}
        public String url{get;set;}
        public String ein{get;set;}
        public String duns{get;set;}
        public String phone{get;set;}
        public Boolean minorityOwned{get;set;}
        public Boolean women{get;set;}
        public Boolean minorityWomen{get;set;}
        public Boolean hubzone{get;set;}
        public Boolean veteran{get;set;}
        public Boolean disabled{get;set;}
        public String sfId{get;set;}

    }

	public class Award {
    
        public String id{get;set;}
        public String sfId{get;set;}
        public String type{get;set;}
        public String contract{get;set;}
        public String proposal{get;set;}
        public String title{get;set;}
        public String agency{get;set;}
        public String program{get;set;}
        public String phase{get;set;}
        public Integer amount{get;set;}
        public String solicitation{get;set;}
        public String techArea{get;set;}
        public String contact_status{get;set;}        
    }

    public class Contact {
    
        public String firstName{get;set;}
        public String lastName{get;set;}
        public String phone {get;set;}
        public String email {get;set;}
        public String id {get;set;}
        public String sfId {get;set;}
        public String role {get;set;}   
    }   

}